// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // Migrate/introspection go through the direct (non-pooled) connection —
  // Neon's PgBouncer pooler doesn't support the shadow-database operations
  // Migrate needs. The app itself still talks to the pooled DATABASE_URL
  // at runtime via lib/prisma.ts; this only affects the CLI.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
